pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp ui/index.html public/index.html
    - cp ui/api_view.html public/
    - cp ui/node.html public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
